### ISSUE TITLE
Dashboard API endpoint return 500

### ISSUE THREAD

**Issue by huedaya** [philippdormann/umami-sqlite#1]
Successfully running this repo, but still stuck in 500 while accessing `/dashboard`, but the `/realtime` works fine. Here's some logs from `docker logs`

```
app-main-umami  | Error: Unknown database.
app-main-umami  |     at rawQuery (/app/.next/server/pages/api/auth/verify.js:492:27)
app-main-umami  |     at getPageviewStats (/app/.next/server/pages/api/auth/verify.js:750:10)
app-main-umami  |     at module.exports.cmhW.__webpack_exports__.default (/app/.next/server/pages/api/website/[id]/pageviews.js:1136:130)
app-main-umami  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
app-main-umami  |     at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
app-main-umami  |     at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:67:462)
app-main-umami  |     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:492)
app-main-umami  |     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
app-main-umami  |     at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042)
app-main-umami  |     at async Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:34:504)
app-main-umami  | Error: Unknown database.
app-main-umami  |     at rawQuery (/app/.next/server/pages/api/auth/verify.js:492:27)
app-main-umami  |     at getPageviewStats (/app/.next/server/pages/api/auth/verify.js:750:10)
app-main-umami  |     at module.exports.cmhW.__webpack_exports__.default (/app/.next/server/pages/api/website/[id]/pageviews.js:1136:130)
app-main-umami  |     at runMicrotasks (<anonymous>)
app-main-umami  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
app-main-umami  |     at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
app-main-umami  |     at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:67:462)
app-main-umami  |     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:492)
app-main-umami  |     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
app-main-umami  |     at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042)
app-main-umami  | Error: Unknown database.
app-main-umami  |     at rawQuery (/app/.next/server/pages/api/auth/verify.js:492:27)
app-main-umami  |     at getActiveVisitors (/app/.next/server/pages/api/auth/verify.js:820:10)
app-main-umami  |     at module.exports.abFk.__webpack_exports__.default (/app/.next/server/pages/api/website/[id]/active.js:1120:103)
app-main-umami  |     at runMicrotasks (<anonymous>)
app-main-umami  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
app-main-umami  |     at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
app-main-umami  |     at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:67:462)
app-main-umami  |     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:492)
app-main-umami  |     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
app-main-umami  |     at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042)
app-main-umami  | Error: Unknown database.
app-main-umami  |     at rawQuery (/app/.next/server/pages/api/auth/verify.js:492:27)
app-main-umami  |     at getWebsiteStats (/app/.next/server/pages/api/auth/verify.js:723:10)
app-main-umami  |     at module.exports.Exqk.__webpack_exports__.default (/app/.next/server/pages/api/website/[id]/stats.js:144:102)
app-main-umami  |     at runMicrotasks (<anonymous>)
app-main-umami  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
app-main-umami  |     at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
app-main-umami  |     at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:67:462)
app-main-umami  |     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:492)
app-main-umami  |     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
app-main-umami  |     at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042)
```

Still wondering what I can do to fix this things up. :thinking:

**Comment by philippdormann** [comment]
Hi there 👋
honestly, this fork is massively out of date and not compatible with the latest umami version.
you should probably take a look at https://github.com/umami-software/umami/pull/1292 😉
